#
# downloads.yml - Use the EAD's <unitid> as the primary key and
#                 provide the PDF and/or EAD (.xml) links. The
#                 size value should be a String (shown as-is) or
#                 the number of bytes in the download.
#
sample_unitid:
  pdf:
    href: 'http://example.com/sample.pdf'
    size: '1.23MB'
  ead:
    href: 'http://example.com/sample.xml'
    size: 123456
default:
  disabled: true
0234 Aa 2:
  ead:
    href: 'https://github.com/sul-dlss/arclight-demo/raw/master/data/ead/umich-bhl/umich-bhl-0234.xml'
    size: 91781
2016C32:
  ead:
    href: 'https://github.com/sul-dlss/arclight-demo/raw/master/data/ead/hoover/2016C32.xml'
    size: 60212
  pdf:
    href: 'http://pdf.oac.cdlib.org/pdf/hoover/2016C32.pdf'
    size: '141.75 KB'
rosenberg:
  ead:
    template: 'https://quod.lib.umich.edu/s/sclead/eads/%{collection_unitid}.xml'
