hoover:
  name: 'Hoover Institution Archives'
  description: 'Founded by Herbert Hoover in 1919, the Hoover Institution Library & Archives are dedicated to documenting war, revolution, and peace in the twentieth and twenty-first centuries. With nearly one million volumes and more than six thousand archival collections from 171 countries, Hoover supports a vibrant community of scholars and a broad public interested in the meaning and role of history.'
  building: ''
  address1: '434 Galvez Mall'
  address2: 'Stanford University'
  city: 'Stanford'
  state: 'CA'
  zip: '94305-6003'
  phone: '650-723-1754'
  contact_info: ''
  thumbnail_url: 'https://www.hoover.org/sites/default/files/styles/one_by_one/public/library/slides/poster_rusu_02237.jpg'
  visit_note: 'Archival holdings are brought from the stacks to the reading room at 9:00 a.m., 10:30 a.m., 11:30 a.m., 1:30 p.m., and 3:00 p.m. Some of the archives’ collections are stored off-site.'

nlm:
  name: 'National Library of Medicine. History of Medicine Division'
  description: 'NLM’s History of Medicine Division collects, preserves, makes available, and interprets for diverse audiences one of the world’s richest collections of historical material related to human health and disease.'
  building: 'Building 38, Room 1E-21'
  address1: '8600 Rockville Pike'
  address2: ''
  city: 'Bethesda'
  state: 'MD'
  zip: '20894'
  country: 'USA'
  phone: ''
  contact_info: 'hmdref@nlm.nih.gov'
  thumbnail_url: "https://collections.nlm.nih.gov/pageturnerserver/ajaxp?theurl=http://localhost:8080/fedora/get/nlm:nlmuid-101421040-img/THUMB"
  google_request_url: 'https://docs.google.com/a/stanford.edu/forms/d/e/1FAIpQLSeOamhY_IcFw4sPnz0ddwWWkrPaHbM5wp7JVbOLOL_mIusEyw/viewform'
  google_request_mappings: "document_url=entry.1980510262&collection_name=entry.619150170&collection_creator=entry.14428541&eadid=entry.996397105&containers=entry.1125277048&title=entry.862815208"

sul-ars:
  name: 'Stanford University Libraries. Archive of Recorded Sound'
  visit_note: 'The Archive’s materials are for on-site use only. It is advised that visitors contact the Archive in advance so that required materials can be prepared.'
  description: 'The Archive of Recorded Sound’s collection contains over 400,000 items that span sound recording history--from its beginnings to the present day. Nearly all formats ever developed to record sound are represented: piano rolls; wax cylinders; shellac, acetate, aluminum, and vinyl discs; magnetic wire and tape recordings; compact discs. Collections are particularly strong in the areas of jazz and opera.'
  building: 'Braun Music Center'
  address1: '541 Lasuen Mall'
  address2: ''
  city: 'Stanford'
  state: 'CA'
  zip: '94305-3076'
  country: 'USA'
  phone: ''
  contact_info: 'soundarchive@stanford.edu'
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/branch/image/Edison_002LowRes.jpg'

sul-spec:
  name: 'Stanford University Libraries. Special Collections and University Archives'
  visit_note: 'Special Collections and University Archives materials are stored offsite and must be paged 36 hours in advance.'
  description: 'The Special Collections and University Archives Department of Stanford University Libraries is committed to acquiring, preserving, and providing access to primary source materials that support the research needs of the Stanford community and beyond. There are three distinct divisions in our department: Manuscripts, Rare Books and University Archives. We welcome all students, scholars and members of the general public to the Field Reading Room. Learn more about using and accessing our collections.'
  building: 'Green Library'
  address1: '557 Escondido Mall'
  address2: ''
  city: 'Stanford'
  state: 'CA'
  zip: '94305'
  country: 'USA'
  phone: '(650) 725-1022'
  contact_info: 'specialcollections@stanford.edu'
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/collection/image/Collections-Super-Enlight.jpg'

umich-bhl:
  name: 'University of Michigan. Bentley Historical Library'
  description: 'The Bentley Historical Library collects the materials for and promotes the study of the histories of two great, intertwined institutions, the State of Michigan and the University of Michigan. The Library is open without fee to the public, and we welcome researchers regardless of academic or professional affiliation.'
  building: ''
  address1: '1150 Beal Ave'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109-2113'
  country: 'USA'
  phone: ''
  contact_info: 'bentley.ref@umich.edu'
  thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Bhlexterior.jpg/150px-Bhlexterior.jpg'
